function [F,R] = primerselect(i)
if i == 1
    F = 'TTCGTTCGTCGTTGATTGGT'; 
    R = 'AAACGGAGCCATGAGTTTGT';
elseif i == 2
    F = 'AAATCCTTTGTGCCTGCCAT'; 
    R = 'AAACTCAAGGCCGACCAATT';
elseif i == 3
    F = 'AATCATGGCCTTCAAACCGT'; 
    R = 'AACGCTCCGAAAGTCTTGTT';
elseif i == 4
    F = 'CTGTCCATAGCCTTGTTCGT'; 
    R = 'GCGGAAACGTAGTGAAGGTA';
elseif i == 5
    F = 'TGTATTTCCTTCGGTGCTCC'; 
    R = 'TTTCGACAACGGTCTGGTTT'; 
elseif i == 6
    F = 'AGCCTTGTGTCCATCAATCC'; 
    R = 'TGCGCTATGGTTTGGCTAAT';
elseif i == 7
    F = 'GTCCAGGCAAAGATCCAGTT'; 
    R = 'ACCACCGTTAGGCTAAAGTG';
elseif i == 8
    F = 'ATCCTGCAAACGCATTTCCT'; 
    R = 'ATGCCTTTCCGAAGTTTCCA';
elseif i == 9
    F = 'TAGCCTCCAGAATGAAACGG'; 
    R = 'TTCAAGCCAAACCGTGTGTA'; 
elseif i == 10
    F = 'TCCTCAGCCGATGAAATTCC';
    R = 'TGTACCATCCGTTTGACTGG';
elseif i == 11
    F = 'TACCGCATCCTTATTCGAGC';
    R = 'TCTGGTGCAAGCCAATGAAA';
elseif i == 12
    F = 'GAAGAGTTTAGCCACCTGGT';
    R = 'AAGGCCAATTCGCGGTTATT';
elseif i == 13
    F = 'CAAGATTGTGGACGATTGGC';
    R = 'TGCAATGTTTCCGTCGGTTT';
 elseif i == 14
    F = 'ATGCACTCAGACGTACAACG';
    R = 'CATTACACCTCACGCCTTCG';
elseif i == 15
    F = 'GTACTGCCATCGACACTGGC';
    R = 'GTACACCTCACGCCTTCACC';
elseif i == 16
    F = 'GCACTTACCTCAACATACCC';
    R = 'GCGTCTAACCTGGGATGCAC';  
end